### PR TITLE
More Code Review

### PR DESCRIPTION
**Pull request by Cabalist**
Hello again!

Same thing as last time.  There should be NO functionality change at all.  Some of the long string formatting changes you should verify but they evaluate the same on my machine.    File are now closed automatically, paths are handled in a more secure/error proof way, now more `import *` and a bunch of whitespace stuff.

Let me know if these pass mustard and I'll start attacking some of the larger modules.

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
On commit https://github.com/Cabalist/social-engineer-toolkit/commit/ba47bd0355552e6b2cf77c320dd3161c566608c8 can you fix the {} to {0} etc please as this is a python best practice

**Comment by Cabalist** [comment]
@L1ghtn1ng  Done.

Oops.  That QRcode change wasn't supposed to be added here but I accidently got it in the mix.  Check that out too I guess.   It should be fine unless there was something custom about the bundled qrcode.py.

**Comment by Cabalist** [comment]
Also:  I meant "pass muster" but wrote "pass mustard".  Can't even blame autocorrect. *sigh*

**Comment by trustedsec** [comment]
Lol - it passes mustard, thanks =) Appreciate all the help and cleaning it up.

**Comment by carmonaadobe903-tech** [comment]
olá boa noite gostaria de a prender mais convosco o que faço

**Pull request merged**
