### PR TITLE
powershell module Python3, Pep8 and modularizing

### PR DESCRIPTION
**Pull request by Cabalist**
Same as before.  

The only other thing I did here is put the powershell prep module into a function so that instead of trying to reload a module in various scripts it imports it once and then the function is called if necessary.  This may have other implications in a project of this size but I want to roll this out and see if it worked.  

More eyes are wanted.

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
I think it would be better to have a powershell class than having a massive function as then it would be split into more manageable method functions

**Comment by Cabalist** [comment]
Great! I agree it would be better as a class instead of just dumping it all
in a function but this gets rid of the module reloading in the short term
as it is refactored.

**Comment by trustedsec** [comment]
I'm still working on this one, the addition to modular powershell injection broke this module completely and doesn't generate the appropriate base64 encoded code - i like going through and becoming more modular, when I originally wrote set it wasn't this way.. will need to revert this one completely back unless I can figure it out.

**Comment by Cabalist** [comment]
I'll take another look at this and see if I can write some tests to make
sure it doesn't happen again.

**Comment by trustedsec** [comment]
Yeah, it broke the entire powershell injection stuff (may work in python3 dunno, but def not in python2).

It looks to be similar from previous ones I've had to change. Looks like the join stuff again where the join statement isn't properly doing things like for example where it checks to see if the pyinjector file is there - it doesn't work so I have to fix that statement and it turns it off otherwise it thinks pyinjector is there. I'm reverting this one back for now. I spent an hour playing with it and got it about half way there but not all the way.

**Comment by Cabalist** [comment]
I'd love some more info about the path stuff.  I know there is one issue I introduced which was not removing the leading slash on some paths but if there is more I'd like to know.

**Comment by Cabalist** [comment]
Is the base64 code generated by `src.core.setcore.generate_powershell_alphanumeric_payload`?

**Comment by trustedsec** [comment]
yeah b64 code is generated out of that one solely

**Comment by trustedsec** [comment]
btw - really appreciate all the changes..removing old crud and doing things properly takes time and a lot of breaking :)

**Comment by Cabalist** [comment]
I must have changed one of the inputs then.  Which is weird cause they are all strings that are set immediately before hand.

If you run the prep.py module by itself does it generate correct results for you?

**Pull request merged**
