### PR TITLE
Pep8 & python3 for html

### PR DESCRIPTION
**Pull request by Cabalist**
Same as before.   I am going to try and touch all the modules first but I am making a list of bug fixes and refactors at the same that I'll start making branches for as well.  I am doing this all incrementally so there is no 20K line pull requests.  :)

### CODE REVIEW

**Comment by trustedsec** [comment]
I'm not going to accept these for right now.. There is a lot of breakage going on here, right now powershell injection, mssql, and psexec with powershell is broke. I'm teaching a class so I'm trying to fix them as soon as I can. Going to hold off on these for a bit.

**Comment by Cabalist** [comment]
Understood.

**Comment by trustedsec** [comment]
Sorry, recovering from BH/DC =) I'll get these going this week. Really appreciate it.

**Comment by L1ghtn1ng** [comment]
Line 66 you have a typo in the /src/html/spawn.py you have {0{ instead of {0}

**Pull request merged**
