### PR TITLE
Code Review

### PR DESCRIPTION
**Pull request by Cabalist**
These changes are primarily to get the code running on my python3 installation.  Along the way I have modernized some of the code.

I did some of the top level files and haven't moved further in because I wanted to see if you were open to this type of pull request.   Let me know if you would like to see more of this.

To Summarize the biggest changes to style were:
- No more `import *`.  This complicates the namespace and I used the `import src.core.setcore as core` pattern that I found in other parts of the code to replace it.
- `os.path.join` is now used instead of string concatenation for most paths
- replaced raw_input with an input alias on Py2 and just input on Py3
- Replaced file.open() and file.close() with contextmanagers (i.e. `with open(path) as fileopen:`

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
Code looks good to me

**Comment by trustedsec** [comment]
Very much open to this and really appreciate it. I'm literally about to release on Monday a major/extensive version of SET. I'll have some major merge conflicts - can you resubmit after I do the push on Monday?  All of this looks good to me and again - much appreciated =)

**Comment by Cabalist** [comment]
Yeah.  No problem.  This is why I check first.  :)

**Comment by trustedsec** [comment]
Looks like this will merge, going to snag it and take a peek.

**Comment by Cabalist** [comment]
Cool.  Expect more.  :)

**Pull request merged**
